
services:
  camaroesapp:
    container_name: camaroesapp
    image: buenolas/camaroesapp:1.1.1
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  vite:
    image: node:20
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true

  db:
    container_name: database
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:   
  pgdata: {}